version: "3.9"

services:
  db:
    image: postgres:16
    container_name: insuraflow_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: insuraflow_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/app
      - /dev/null:/app/.env.local
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
