# Generated by Django 6.0.2 on 2026-04-01 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_policyplan_userpolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='insurer',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='insurer',
        ),
        migrations.RemoveField(
            model_name='policyplan',
            name='insurer',
        ),
        migrations.RemoveField(
            model_name='userpolicy',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='policy_holder',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='policy_number',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='status',
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='title',
            field=models.CharField(default='New Policy', max_length=100),
        ),
        migrations.AddField(
            model_name='surveyor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveyor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_policies', to='insurance.agent'),
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='insurance.policy'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('health', 'Health'), ('motor', 'Motor'), ('life', 'Life'), ('travel', 'Travel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('registration_no', models.CharField(max_length=100, unique=True)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('head_office_address', models.TextField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='insurance.provider'),
        ),
        migrations.AddField(
            model_name='policy',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insurance.provider'),
        ),
        migrations.DeleteModel(
            name='Insurer',
        ),
        migrations.DeleteModel(
            name='PolicyPlan',
        ),
    ]
