# Generated by Django 6.0.2 on 2026-04-02 08:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_remove_policy_insurer_remove_agent_insurer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpolicy',
            unique_together={('user', 'policy')},
        ),
    ]
