# Generated by Django 6.0.2 on 2026-04-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_alter_userpolicy_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['id']},
        ),
    ]
