"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import quote_plus, urlparse

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Explicitly load .env files from the same directory as manage.py.
# `.env.local` is loaded last so it can override the shared defaults in `.env`.
ENV_PATH = BASE_DIR / ".env"
ENV_LOCAL_PATH = BASE_DIR / ".env.local"

if ENV_PATH.exists():
    load_dotenv(ENV_PATH, override=True)

if ENV_LOCAL_PATH.exists():
    load_dotenv(ENV_LOCAL_PATH, override=True)


def get_env_list(name, default):
    value = os.getenv(name)
    if not value:
        return default
    return [item.strip() for item in value.split(",") if item.strip()]


def unique(values):
    return list(dict.fromkeys(values))


def is_truthy(value):
    return str(value).lower() in ["true", "1", "yes", "on"]


def build_local_database_url():
    name = os.getenv("DB_NAME")
    user = os.getenv("DB_USER")
    password = os.getenv("DB_PASS")
    host = os.getenv("DB_HOST", "localhost")
    port = os.getenv("DB_PORT", "5432")

    if not name or not user:
        return None

    encoded_user = quote_plus(user)
    encoded_password = quote_plus(password or "")
    auth_part = f"{encoded_user}:{encoded_password}" if password else encoded_user

    return f"postgresql://{auth_part}@{host}:{port}/{name}"


def is_render_internal_database_url(value):
    if not value:
        return False

    try:
        hostname = urlparse(value).hostname or ""
    except Exception:
        return False

    # Render internal Postgres hostnames are private and not reachable from a local machine.
    return hostname.startswith("dpg-") and "." not in hostname


def should_require_db_ssl(value):
    if not value:
        return False

    try:
        hostname = (urlparse(value).hostname or "").lower()
    except Exception:
        return False

    return hostname not in {"localhost", "127.0.0.1", "::1"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY=os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = is_truthy(os.getenv("DEBUG", "False"))

ALLOWED_HOSTS = get_env_list("ALLOWED_HOSTS", ["*"])
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173").rstrip("/")
RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME")
IS_RENDER = is_truthy(os.getenv("RENDER", "")) or bool(RENDER_EXTERNAL_HOSTNAME)
ENABLE_HTTPS_SECURITY = is_truthy(
    os.getenv("ENABLE_HTTPS_SECURITY", "True" if IS_RENDER else "False")
)

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS = unique([*ALLOWED_HOSTS, RENDER_EXTERNAL_HOSTNAME])
    render_origin = f"https://{RENDER_EXTERNAL_HOSTNAME}"
else:
    render_origin = None

# Security Settings (enable when using HTTPS in production)
if ENABLE_HTTPS_SECURITY:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'django_filters',
    'accounts',
    'insurance',
    'claims',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.RequestLogMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

database_url = os.getenv("DATABASE_URL")

if (
    database_url
    and is_render_internal_database_url(database_url)
    and not os.getenv("RENDER")
    and not os.getenv("RENDER_EXTERNAL_HOSTNAME")
):
    database_url = None

database_url = database_url or build_local_database_url()

if database_url:
    DATABASES = {
        'default': dj_database_url.parse(
            database_url,
            conn_max_age=600,
            ssl_require=should_require_db_ssl(database_url)
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("DB_NAME"),
            'USER': os.getenv("DB_USER"),
            'PASSWORD': os.getenv("DB_PASS"),
            'HOST': os.getenv("DB_HOST", "localhost"),
            'PORT': os.getenv("DB_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

AUTH_USER_MODEL = 'accounts.User'

from datetime import timedelta

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "config.exceptions.custom_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS":"rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),   
}

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = is_truthy(os.getenv("CORS_ALLOW_ALL_ORIGINS", "True"))
CORS_ALLOWED_ORIGINS = unique(get_env_list("CORS_ALLOWED_ORIGINS", [
    FRONTEND_URL,
    "http://127.0.0.1:5173",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://localhost:3000",
    *([render_origin] if render_origin else []),
]))
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = unique(get_env_list("CSRF_TRUSTED_ORIGINS", [
    FRONTEND_URL,
    "http://127.0.0.1:5173",
    "http://localhost:5173",
    *([render_origin] if render_origin else []),
]))

SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'


# Secret keys for registering special roles.
# These are hardcoded so deployment env drift cannot block privileged account creation.
ADMIN_SECRET_KEY = "admin-secret-2026"
AGENT_SECRET_KEY = "agent-secret-2026"
PROVIDER_SECRET_KEY = "provider-secret-2026"
SURVEYOR_SECRET_KEY = "surveyor-secret-2026"

REGISTER_SECRET_KEY = "insuraflow-secret-2026"  # Fallback or shared

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
        'config.middleware': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
