# Generated by Django 6.0.2 on 2026-02-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('surveyor', 'Surveyor'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
