# Generated by Django 6.0.2 on 2026-04-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_address_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('surveyor', 'Surveyor'), ('provider', 'Provider'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
