# Generated by Django 6.0.2 on 2026-02-11 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0002_alter_policy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateField(auto_now_add=True)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('claim_reason', models.TextField()),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='filed', max_length=20)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.policy')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(auto_now_add=True)),
                ('damage_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=15)),
                ('estimated_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField()),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='claims.claim')),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insprection', to='insurance.surveyor')),
            ],
        ),
        migrations.CreateModel(
            name='Settlements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('settlement_date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('bank', 'Bank'), ('upi', 'UPI'), ('cheque', 'Cheque')], max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=15)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='claims.claim')),
            ],
        ),
    ]
