# Generated by Django 6.0.2 on 2026-02-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settlements',
            new_name='Settlement',
        ),
    ]
