# Generated by Django 6.0.2 on 2026-03-29 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_claim_status'),
        ('insurance', '0002_alter_policy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='surveyor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection', to='insurance.surveyor'),
        ),
    ]
