# Generated by Django 6.0.2 on 2026-04-01 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_alter_inspectionreport_surveyor'),
        ('insurance', '0004_remove_policy_insurer_remove_agent_insurer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='policy',
        ),
        migrations.AddField(
            model_name='claim',
            name='assigned_surveyor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_claims', to='insurance.surveyor'),
        ),
        migrations.AddField(
            model_name='claim',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='claims/'),
        ),
        migrations.AddField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='user_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.userpolicy'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='inspections/'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='claims.claim'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='surveyor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='insurance.surveyor'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='claims.claim'),
        ),
    ]
